"""Torque bounded joint servo + inverse-dynamics feedforward + optional IMU attitude feedback."""
from quasistatic import *
import argparse
from scipy.spatial.transform import Slerp

def run(a):
 ffpath=ROOT/a.trajectory;source=json.loads(ffpath.read_text());ss=source['samples'];times=np.array([s['time_s']for s in ss]);ev=StaticEvaluator(ROOT/a.model if a.model else MODEL,ROOT/a.contract if a.contract else CONTRACT);m,d=ev.m,ev.d;names=ev.names;qids=ev.qids;vids=ev.vids;aids=np.array([m.actuator(n+'_torque').id for n in names]);caps=ev.caps;m.opt.timestep=a.dt;m.geom_friction[:,0]=a.friction;kp=np.array([a.xc_kp if j['motor_model']=='XC330' else a.kp for j in ev.c['joints']]);kd=np.array([a.xc_kd if j['motor_model']=='XC330' else a.kd for j in ev.c['joints']]);m.actuator_gainprm[aids,0]=kp;m.actuator_biasprm[aids,1]=-kp;m.actuator_biasprm[aids,2]=-kd
 qs=np.deg2rad([[s['q_HOME_delta_deg'].get(n,0)for n in names]for s in ss]);vs=np.array([[s['joint_qvel_rad_s'][n]for n in names]for s in ss]);ff=np.array([[s['feedforward_torque_Nm'][n]for n in names]for s in ss]);BT=np.array([s['base_transform_m']for s in ss]);Rref=Slerp(times,Rotation.from_matrix(BT[:,:3,:3]));ev.set_state(ss[0]['q_HOME_delta_deg'],BT[0]);d.qpos[2]+=a.initial_clearance_mm/1000;d.qvel[:]=0;d.ctrl[aids]=qs[0]+ff[0]/kp;mujoco.mj_forward(m,d);rootid=m.body('trunk_base').id;records=[];saturated=np.zeros(len(names));sat_run=np.zeros(len(names));max_sat_run=np.zeros(len(names));peaks=np.zeros(len(names));sum2=np.zeros(len(names));maxqerror=np.zeros(len(names));maxforceover=0;steps=0;reason='COMPLETED';maximu=np.zeros(len(names));duration=min(a.duration or times[-1],times[-1]);initial=d.qpos.copy();previous=None
 assert source['sources'].get(str(ev.model_path.relative_to(ROOT)))==hashlib.sha256(ev.model_path.read_bytes()).hexdigest(),'FF_MODEL_MISMATCH'
 assert source['sources'].get(str(ev.contract_path.relative_to(ROOT)))==hashlib.sha256(ev.contract_path.read_bytes()).hexdigest(),'FF_CONTRACT_MISMATCH'
 maxrooterror_all=0.;interval_rooterror=0.
 intervals=[];bound_start=0.;bound_steps=0;qlow=np.rad2deg(d.qpos[qids]).copy();qhigh=qlow.copy();qstart=qlow.copy();qvmax=np.rad2deg(abs(d.qvel[vids]));rootlow=d.qpos[:3].copy();roothigh=rootlow.copy()
 def flush_bounds():
  nonlocal bound_start,bound_steps,qlow,qhigh,qstart,qvmax,rootlow,roothigh,interval_rooterror
  if not bound_steps:return
  endq=np.rad2deg(d.qpos[qids]);intervals.append(dict(start_s=bound_start,end_s=float(d.time),integration_steps=bound_steps,q_min_HOME_deg=dict(zip(names,qlow.tolist())),q_max_HOME_deg=dict(zip(names,qhigh.tolist())),q_start_HOME_deg=dict(zip(names,qstart.tolist())),q_end_HOME_deg=dict(zip(names,endq.tolist())),maximum_absolute_joint_velocity_deg_s=dict(zip(names,qvmax.tolist())),root_xyz_min_m=rootlow.tolist(),root_xyz_max_m=roothigh.tolist(),maximum_root_reference_orientation_error_deg=interval_rooterror))
  bound_start=float(d.time);bound_steps=0;interval_rooterror=0.;qlow=endq.copy();qhigh=endq.copy();qstart=endq.copy();qvmax=np.rad2deg(abs(d.qvel[vids]));rootlow=d.qpos[:3].copy();roothigh=rootlow.copy()
 def reference(t):
  k=int(np.clip(np.searchsorted(times,t,side='right')-1,0,len(times)-2));u=float(np.clip((t-times[k])/(times[k+1]-times[k]),0,1));return k,u,qs[k]*(1-u)+qs[k+1]*u,vs[k]*(1-u)+vs[k+1]*u,ff[k]*(1-u)+ff[k+1]*u
 def record():
  mujoco.mj_forward(m,d);t=float(d.time);k,u,q,v,tau=reference(t);rr=Rref(np.clip(t,times[0],times[-1]));ra=Rotation.from_matrix(d.xmat[rootid].reshape(3,3));error=np.rad2deg((rr.inv()*ra).magnitude());rp=np.array([np.interp(t,times,BT[:,i,3])for i in range(3)]);force={l:0. for l in ev.feet};contacts=[]
  for ci in range(d.ncon):
   c=d.contact[ci];g1=m.geom(c.geom1).name;g2=m.geom(c.geom2).name;foot=next((l for l in ev.feet if l in g1 or l in g2),None)
   if foot:
    f=np.zeros(6);mujoco.mj_contactForce(m,d,ci,f);force[foot]+=max(0,float(f[0]));contacts.append(dict(foot=foot,pos_m=c.pos.tolist(),normal_force_N=float(f[0]),contact_frame_force_world_N=(c.frame.reshape(3,3).T@f[:3]).tolist(),contact_geom1=g1,contact_geom2=g2,distance_m=float(c.dist)))
  feet={}
  for link,poly in ev.feet.items():
   bid=m.body(link).id;R=d.xmat[bid].reshape(3,3);verts=(poly-ev.pivots[link])@R.T+d.xpos[bid];feet[link]=dict(outline_mean_world_m=verts.mean(0).tolist(),min_z_m=float(verts[:,2].min()),max_z_m=float(verts[:,2].max()),rotation_world=R.tolist())
  records.append(dict(time_s=t,phase=ss[k].get('phase'),contact_mode=ss[k].get('contact_mode'),desired_load_fraction_by_link=ss[k].get('desired_load_fraction_by_link'),support_links=ss[k]['support_links'],q_HOME_delta_deg=dict(zip(names,np.rad2deg(d.qpos[qids]).tolist())),q_target_HOME_delta_deg=dict(zip(names,np.rad2deg(q).tolist())),root_xyz_m=d.qpos[:3].tolist(),root_quaternion_wxyz=d.qpos[3:7].tolist(),root_orientation_error_deg=float(error),root_position_error_mm=((d.qpos[:3]-rp)*1000).tolist(),root_absolute_tilt_deg=float(np.rad2deg(np.arccos(np.clip(d.xmat[rootid].reshape(3,3)[2,2],-1,1)))),COM_world_m=d.subtree_com[rootid].tolist(),foot_normal_force_N=force,contacts=contacts,feet=feet,joint_torque_Nm=dict(zip(names,d.actuator_force[aids].tolist()))));return float(error)
 record()
 for it in range(int(round(duration/a.dt))):
  t=d.time;k,u,q,v,tau=reference(t);imu=np.zeros(len(names))
  if a.imu_gain:
   # Only orientation/gyro and encoded joints enter this feedback; no root position force.
   mujoco.mj_forward(m,d);support=ss[k]['support_links'][0];bid=m.body(support).id;point=d.xpos[bid];jp=np.zeros((3,m.nv));jr=np.zeros((3,m.nv));mujoco.mj_jac(m,d,jp,jr,point,bid);J=np.vstack([jp,jr]);base_from_joint=-np.linalg.solve(J[:,:6],J[:,vids]);rootJp=np.zeros((3,m.nv));rootJr=np.zeros((3,m.nv));mujoco.mj_jac(m,d,rootJp,rootJr,d.xpos[rootid],rootid);D=rootJr[:,:6]@base_from_joint+rootJr[:,vids];ra=Rotation.from_matrix(d.xmat[rootid].reshape(3,3));rr=Rref(np.clip(t,times[0],times[-1]));e=(rr*ra.inv()).as_rotvec();expectedw=rootJr[:,:6]@np.array(ss[k]['generalized_velocity'])[:6];actualw=rootJr@d.qvel;imu=D.T@(a.imu_gain*e-a.imu_damping*(actualw-expectedw));imu=np.clip(imu,-.18,.18)
  maximu=np.maximum(maximu,abs(imu));d.ctrl[aids]=q+(kd/kp)*v+(tau+imu)/kp;maxqerror=np.maximum(maxqerror,abs(q-d.qpos[qids]));mujoco.mj_step(m,d);actual=d.actuator_force[aids];sat=np.abs(actual)>=caps-1e-9;saturated+=sat;sat_run=np.where(sat,sat_run+1,0);max_sat_run=np.maximum(max_sat_run,sat_run);peaks=np.maximum(peaks,abs(actual));sum2+=actual**2;steps+=1;maxforceover=max(maxforceover,float(np.max(abs(actual)-caps)))
  qdegrees=np.rad2deg(d.qpos[qids]);qlow=np.minimum(qlow,qdegrees);qhigh=np.maximum(qhigh,qdegrees);qvmax=np.maximum(qvmax,np.rad2deg(abs(d.qvel[vids])));rootlow=np.minimum(rootlow,d.qpos[:3]);roothigh=np.maximum(roothigh,d.qpos[:3]);bound_steps+=1
  allerror=float(np.rad2deg((Rref(np.clip(d.time,times[0],times[-1])).inv()*Rotation.from_quat(d.qpos[[4,5,6,3]])).magnitude()));maxrooterror_all=max(maxrooterror_all,allerror);interval_rooterror=max(interval_rooterror,allerror)
  _,_,postq,_,_=reference(d.time);maxqerror=np.maximum(maxqerror,abs(postq-d.qpos[qids]))
  if it%max(1,round(.02/a.dt))==max(1,round(.02/a.dt))-1:error=record();flush_bounds()
  else:error=np.rad2deg((Rref(np.clip(d.time,times[0],times[-1])).inv()*Rotation.from_quat(d.qpos[[4,5,6,3]])).magnitude())
  if error>20 or d.qpos[2]<initial[2]*.6:reason='ORIENTATION_ERROR_GT20_OR_HEIGHT_LOSS_STOP';record();break
 if records[-1]['time_s']<d.time-1e-8:record()
 flush_bounds()
 target=OUT/a.name;target.mkdir(parents=True,exist_ok=True);srcs=dict(source['sources']);srcs[str(ffpath.relative_to(ROOT))]=hashlib.sha256(ffpath.read_bytes()).hexdigest();srcs[str(Path(__file__).relative_to(ROOT))]=hashlib.sha256(Path(__file__).read_bytes()).hexdigest();srcs[str(ev.model_path.relative_to(ROOT))]=hashlib.sha256(ev.model_path.read_bytes()).hexdigest();srcs[str(ev.contract_path.relative_to(ROOT))]=hashlib.sha256(ev.contract_path.read_bytes()).hexdigest();report=dict(status=reason,physical_approved=False,requested_duration_s=float(duration),simulated_duration_s=float(d.time),mass_kg=sum(m.body_mass),max_root_orientation_error_deg=maxrooterror_all,max_saved_root_orientation_error_deg=max(r['root_orientation_error_deg']for r in records),final_root_position_error_mm=records[-1]['root_position_error_mm'],maximum_torque_limit_excess_Nm=maxforceover,parameters=vars(a),actuators=[dict(joint=n,cap_Nm=float(caps[i]),kp_Nm_rad=float(kp[i]),kd_Nm_s_rad=float(kd[i]),peak_Nm=float(peaks[i]),RMS_Nm=float(np.sqrt(sum2[i]/steps)),saturated_fraction=float(saturated[i]/steps),max_continuous_saturation_s=float(max_sat_run[i]*a.dt),max_tracking_error_deg=float(np.rad2deg(maxqerror[i])),max_IMU_correction_Nm=float(maximu[i]))for i,n in enumerate(names)],sources=srcs)
 bounds=dict(status='ENCLOSURE_OF_ALL_NUMERICAL_INTEGRATION_STATES_AND_LINEAR_JOINT_CONNECTIONS',physical_approved=False,note='Every integration endpoint, including shared interval endpoints, contributes to min/max; this is not a continuous real-hardware trajectory proof.',dt_s=a.dt,interval_count=len(intervals),total_integration_steps=steps,intervals=intervals,sources=srcs)
 (target/'interval_joint_bounds.json').write_text(json.dumps(bounds,ensure_ascii=False,indent=2)+'\n')
 (target/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');(target/'trajectory.json').write_text(json.dumps(dict(status='ACTUALLY_INTEGRATED_FREE_BASE_DIAGNOSTIC',samples=records,sources=srcs,physical_approved=False),ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:report[k]for k in ['status','simulated_duration_s','max_root_orientation_error_deg','final_root_position_error_mm','maximum_torque_limit_excess_Nm']},ensure_ascii=False));print('PEAKS',[(x['joint'],round(x['peak_Nm'],3),round(x['max_tracking_error_deg'],3),round(x['saturated_fraction'],4))for x in report['actuators']if x['saturated_fraction']>.001 or x['max_tracking_error_deg']>1])
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--trajectory',required=True);ap.add_argument('--name',required=True);ap.add_argument('--model');ap.add_argument('--contract');ap.add_argument('--duration',type=float);ap.add_argument('--dt',type=float,default=.00025);ap.add_argument('--friction',type=float,default=.8);ap.add_argument('--kp',type=float,default=80);ap.add_argument('--kd',type=float,default=2);ap.add_argument('--xc-kp',type=float,default=20);ap.add_argument('--xc-kd',type=float,default=.2);ap.add_argument('--initial-clearance-mm',type=float,default=0);ap.add_argument('--imu-gain',type=float,default=0);ap.add_argument('--imu-damping',type=float,default=.1);run(ap.parse_args())
