from pathlib import Path
import json,hashlib,math,datetime
R=Path(__file__).parent;V=R/'verification';BASE=R.parents[2]
new={h:json.loads((V/f'dc_flow_r22_{h}.json').read_text())for h in [.1,.075]}
source={.1:json.loads((V/'dc_flow_source_regen_0.1.json').read_text()),.075:json.loads((V/'dc_flow_source_regen_0.075.json').read_text())}
sp={h:json.loads((V/f'dc_flow_source_power_{h}.json').read_text())[0]for h in [.1,.075]}
rows=[]
for i,fine in enumerate(new[.075]):
 coarse=new[.1][i];ss=source[.075][i] if i<4 else source[.075][3]
 rows.append({'net':fine['net'],'from':fine['from_pins'],'to':fine['to_pins'],'R20_0p10_mOhm':coarse['R20_mOhm'],'R20_0p075_mOhm':fine['R20_mOhm'],'grid_difference_percent':100*abs(coarse['R20_mOhm']/fine['R20_mOhm']-1),'source_regen_corresponding_R20_0p075_mOhm':ss['R20_mOhm'],'solver_residual':fine['residual_relative'],'solver_info':fine['solver_info']})
arr=[]
for h in [.1,.075]:
 aa=[q for q in new[h][0]['via_flows']if 30<q['pos'][0]<34 and 7<q['pos'][1]<9];shares=[q['layer_current_fraction'][1]for q in aa]
 arr.append({'grid_mm':h,'sum_current_fraction':sum(shares),'maximum_fraction':max(shares),'minimum_fraction':min(shares),'coefficient_of_variation':(sum((x-sum(shares)/len(shares))**2 for x in shares)/len(shares))**.5/(sum(shares)/len(shares)),'rows':aa})
new_loop=sum(r['R20_mOhm'] for r in new[.075][:4]);old_loop=sum(r['R20_mOhm']for r in source[.075])+sp[.075]['R20_mOhm'];i=12/.99
result={'status':'APPROXIMATE DC GEOMETRY SCREEN; NOT ELECTROTHERMAL OR HARDWARE ACCEPTANCE','method':{'geometry':'All native filled-zone contours and holes; actual pad polygons; tracks; every relevant plated via and THT barrel. 32 distributed barrel sectors; named pad boundaries ideal1V/0V.','source_layers_mm':[.07,.07],'new_layers_mm':[.07,.035,.035,.07],'via_wall_min_assumed_mm':.025,'copper_rho20_ohm_mm':1.7241e-5,'grid_mm':[.1,.075],'linear_solve':'Sparse direct for small systems; algebraic multigrid preconditioned CG for large GND systems, residual target1e-9; preconditioner changes speed, not the DC equations.','external':'No external wire, connector contact, resistor, MOS or shunt resistance is in the copper solve. No simultaneous servo and regen/logic ground injections.'},'new_paths':rows,'source_power_W4_to_W2_GND_R20_mOhm':sp[.075]['R20_mOhm'],'transition_array_sharing':arr,'full_selected_copper_loop':{'new_W3_RH_MOS_shunt_to_W2_R20_mOhm':new_loop,'source_two_board_copper_R20_mOhm_excluding_interboard_pair':old_loop,'difference_before_removed_interboard_wire_mOhm':new_loop-old_loop,'comparison_limit':'Source path includes Regen copper and Power W4-W2 return, but omits the original two board-to-board wires. New path replaces those wires. Overall resistance comparison cannot be concluded until their actual wire/contact resistance is provided.'},'conditional_12V_over_0p99ohm':{'current_A':i,'new_selected_copper_drop_V':i*new_loop/1000,'new_selected_copper_loss20_W':i*i*new_loop/1000,'new_selected_copper_loss75_W':i*i*new_loop/1000*(1+.00393*55),'new_ground_W2_drop_V':i*new[.075][3]['R20_mOhm']/1000,'new_ground_W2_loss20_W':i*i*new[.075][3]['R20_mOhm']/1000,'transition_max_via_A':i*arr[1]['maximum_fraction'],'meaning':'Only if bus<=12V and external resistor>=.99ohm. This does not establish achieved clamp upper voltage, pulse length or permitted sustained current.'},'ground_flow_screens':[],'limits':['Grid extrema are numerical spread, not guaranteed manufacturing bounds. The short source-to-shunt neck has about7% grid sensitivity and must not be quoted as precision resistance.','PTH barrels including P101 are internal cross-layer conductors; modeled barrel current is NOT the current assigned to its external signal wire.','Global trace/pour connectivity is verified, but local peak current-density cells near ideal pad boundaries are mesh-dependent and are not a current rating.','25um hole copper is an assumption requiring explicit fabrication acceptance and microsection verification.','The original20J/60J energy screen is not a measured physical I2t bound. No transient, low-battery, thermal or motion sample testing was performed.']}
for row in new[.075][3:]:
 vs=row['via_flows'];result['ground_flow_screens'].append({'to':row['to_pins'],'net_current_crossing_layer_boundaries_fraction':[sum(v['layer_current_fraction'][k]for v in vs)for k in range(3)],'largest_internal_barrel_fractions':sorted(vs,key=lambda v:max(abs(x)for x in v['layer_current_fraction']),reverse=True)[:6]})
paths={'new_board':R/'Microduck_Power_Regen_R22.kicad_pcb','source_regen_board':BASE/'work/r13-electronics/inherited/Regen_R8/Microduck_Brake_Control_R8.kicad_pcb','source_power_board':BASE/'work/r13-electronics/inherited/TDK_Power_R8/Microduck_TDK_Power_R8.kicad_pcb'}
paths.update({f'{n}_dc_geometry':V/f'{n}_dc_geometry.json'for n in ['r22','source_regen','source_power']});paths['solver']=R/'solve_power_dc_with_flow.py';result['file_sha256']={n:hashlib.sha256(f.read_bytes()).hexdigest()for n,f in paths.items()};(R/'DC_Copper_Regen_Loop_Final.json').write_text(json.dumps(result,indent=2));print(json.dumps({k:result[k]for k in ['new_paths','full_selected_copper_loop','conditional_12V_over_0p99ohm']},indent=2))
